version: "3"

volumes:
  vendor:

services:
  api:
    build: .
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/abyssparanoia/rapid-go-worker
    ports:
      - "8081:8081"
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
